name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    strategy:
      matrix:
        package: [
          # primary packages
          core,
          engines,

          # seconday packages
          bigint,
          boolean,
          number,
          pick,
          string,

          # tertiary packages
          grandom
        ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            packages/${{ matrix.package }}/package-lock.json

      - name: init
        run: >
          npm ci &&
          npx lerna exec --scope @grandom/${{ matrix.package }} --
          npm ci

      # - name: types
      #   run: >
      #     npx lerna exec --scope @grandom/${{ matrix.package }} --
      #     npm run types

      # - name: lint
      #   run: >
      #     npx lerna exec --scope @grandom/${{ matrix.package }} --
      #     npm run lint

      - name: test
        run: >
          npx lerna exec --scope @grandom/${{ matrix.package }} --
          npm test -- --coverage

  release:
    needs: test

    runs-on: ubuntu-20.04
    timeout-minutes: 10

    # skip the job if the pull request was opened by Dependabot
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            packages/*/package-lock.json

      - name: init
        run: npm ci && npx lerna exec -- npm ci

      # primary packages -----------------------------------------------------------------------------------------------
      - name: core
        run: >
          npx lerna exec --scope @grandom/core -- npm run prep &&
          npx lerna exec --scope @grandom/core -- npx --no-install semantic-release -e semantic-release-monorepo

      - name: engines
        run: >
          npx lerna exec --scope @grandom/engines -- npm run prep &&
          npx lerna exec --scope @grandom/engines -- npx --no-install semantic-release -e semantic-release-monorepo

      # secondary packages ---------------------------------------------------------------------------------------------
      - name: bigint
        run: >
          npx lerna exec --scope @grandom/bigint -- npm run prep &&
          npx lerna exec --scope @grandom/bigint -- npx --no-install semantic-release -e semantic-release-monorepo

      - name: boolean
        run: >
          npx lerna exec --scope @grandom/boolean -- npm run prep &&
          npx lerna exec --scope @grandom/boolean -- npx --no-install semantic-release -e semantic-release-monorepo

      - name: number
        run: >
          npx lerna exec --scope @grandom/number -- npm run prep &&
          npx lerna exec --scope @grandom/number -- npx --no-install semantic-release -e semantic-release-monorepo

      - name: pick
        run: >
          npx lerna exec --scope @grandom/pick -- npm run prep &&
          npx lerna exec --scope @grandom/pick -- npx --no-install semantic-release -e semantic-release-monorepo

      - name: string
        run: >
          npx lerna exec --scope @grandom/string -- npm run prep &&
          npx lerna exec --scope @grandom/string -- npx --no-install semantic-release -e semantic-release-monorepo

      # tertiary packages ----------------------------------------------------------------------------------------------
      - name: grandom
        run: >
          npx lerna exec --scope @grandom/grandom -- npm run prep &&
          npx lerna exec --scope @grandom/grandom -- npx --no-install semantic-release -e semantic-release-monorepo

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
